// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQ8FrxJVLgwhIU6R00elJJKvO9gCvECM',
    appId: '1:604124001900:android:54cd8ef4cc7448ce0f0a49',
    messagingSenderId: '604124001900',
    projectId: 'social-media-test-app-1a749',
    storageBucket: 'social-media-test-app-1a749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYD0No_HPfoW_2iUg-8GtAIlWUcGRTLPI',
    appId: '1:604124001900:ios:6078b948178c34280f0a49',
    messagingSenderId: '604124001900',
    projectId: 'social-media-test-app-1a749',
    storageBucket: 'social-media-test-app-1a749.appspot.com',
    iosClientId: '604124001900-7nl7rnf4itmbs4rrnv6ti7aip4qas1q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.newSocialApp',
  );
}
